/**
 * @desc：定义常量
 */
export default class Constants {

  /**
   * Component size.
   */
  static readonly ICON_SIZE: string = '40%';
  static readonly FULL_PERCENT: string = '100%';
  static readonly BAR_HEIGHT: string = '10%';
  static readonly FULL_SIZE: string = '100%';


  /**
   * Component location.
   */
  static readonly PERCENTAGE_15: string = '15%';
  static readonly PERCENTAGE_25: string = '25%';
  /**
   * Component constants.
   */
  static readonly OPACITY: number = 0.6;
  static readonly BORDER_WIDTH: number = 0.5;

  /**
   * BottomTabIndex
   */
  static readonly HOME_TAB_INDEX = 0;
  static readonly NAV_TAB_INDEX = 1;
  static readonly PROJECT_TAB_INDEX = 2;
  static readonly MSG_TAB_INDEX = 3;
  static readonly MINE_TAB_INDEX = 4;

  /**
   * The width or height of the component is spread across the parent component.
   */
  static readonly FULL_PARENT = '100%';

  /**
   * Shared transition duration.
   */
  static readonly SHARED_DURATION: number = 800;
  /**
   * Page transition exit delay.
   */
  static readonly EXIT_DELAY: number = 100;
}